# Generated by Django 5.1.4 on 2024-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlssalesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default=4.03, max_length=200),
            preserve_default=False,
        ),
    ]
